### ISSUE TITLE
Strange symbols in output

### ISSUE THREAD

**Issue by paulbardack** [rrrene/inch_ex#28]
I see strange letter, is it correct?
<img width="493" alt="bug" src="https://cloud.githubusercontent.com/assets/7769545/17605235/1d865038-6022-11e6-83df-721e5a7bdb18.png">

**Comment by alexdesousa** [comment]
I believe, whatever is causing it, it's the same that's causing the strange output reported in issue #23

**Comment by rrrene** [comment]
Let's continue this in #23 where I just posted a summary of the issue.
