### ISSUE TITLE
Trying to add inch CI to project, got cryptic reference to the movie "war games" instead.

### ISSUE THREAD

**Issue by beckler** [rrrene/inch_ex#40]
Tried running the `mix inchci.add` command and got this:
```
ebay-elixir git:(master) ✗ MIX_ENV=docs mix inchci.add

                         Adding project to Inch CI ...                          

Compiling 1 file (.ex)
Generated ebay app
warning: Mix.Utils.camelize/1 is deprecated, use Macro.camelize/1 instead
  (mix) lib/mix/utils.ex:250: Mix.Utils.camelize/1
  lib/mix/tasks/inch.ex:35: Mix.Tasks.Inch.run/4
  lib/mix/tasks/inchci_add.ex:28: Mix.Tasks.Inchci.Add.add_to_inch_ci/0
  (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
  (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

> Greetings, Professor Falken.

> _

** (MatchError) no match of right hand side value: nil
    lib/inch_ex/setup/readme_badge.ex:26: InchEx.Setup.ReadmeBadge.extract_url/1
    lib/inch_ex/setup/readme_badge.ex:11: InchEx.Setup.ReadmeBadge.run/1
    lib/inch_ex/setup.ex:11: InchEx.Setup.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Pulled out wireshark and figured out that's what you see with you visit [https://inch-ci.org/api/v1/builds](https://inch-ci.org/api/v1/builds)

Followed the TCP stream and got the full request/response since the client makes the request over HTTP instead of HTTPS.

Request: 
```
POST /api/v1/builds HTTP/1.1
content-type: application/json
content-length: 1412
te: 
host: inch-ci.org
connection: keep-alive

{"shell":true,"revision":"58818d84b63e8581aadf908d02a8c41f52233fff","objects":[{"type":null,"source":"lib/ebay.ex:2","object_type":"ModuleObject","moduledoc":...
```

Response: 
```
HTTP/1.1 301 Moved Permanently
Date: Tue, 31 Jan 2017 04:11:35 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d2e733ac5536c3c2db10b8349b065c1a51485835895; expires=Wed, 31-Jan-18 04:11:35 GMT; path=/; domain=.inch-ci.org; HttpOnly
Location: https://inch-ci.org/api/v1/builds
Server: cloudflare-nginx
CF-RAY: 329a520881480d19-ATL

b8
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>

0
```

Come to find out, I believe the core of the issue is that these requests are being made over HTTP instead of HTTPS, and the package is not handling the 3xx response.

Soooo... I'm going to file a PR with what I think are the corrections, but I'm not sure of the implications of the changes, because I don't know if there is a good reason for them to be just plain HTTP.

**Comment by rrrene** [comment]
@beckler Just to be clear: Landing on the endpoint/action which returns the reference to "War Games" was a configuration error. This wasn't me being cheeky, I just wanted to deliver something in every scenario, even the unlikely ones.

Okay, maybe I was being cheeky :neckbeard:

**Comment by beckler** [comment]
@rrrene haha, okay cool! Although I was initially quite confused, I can now appreciate the cheekiness. I initially thought I had stumbled onto some open shell socket/remote execution bug, but luckily that was not the case.
