### ISSUE TITLE
Publish a version compatible with Elixir 1.7 to Hex

### ISSUE THREAD

**Issue by yordis** [rrrene/inch_ex#65]
```
Unfortunately, InchEx 1.x does not support Elixir version above 1.6.x, since the documentation format has changed with Elixir 1.7.0.

If you want to try Inch with Elixir >= v1.7.0, just set the Inch dep to

    {:inch_ex, github: "rrrene/inch_ex"}
```

Rather than forcing me to use the Github version, I would really like to see a Hex version to be published ***because I can't publish my packages to Hex.***

**Comment by rrrene** [comment]
@yordis Sorry for the inconvenience: https://hex.pm/packages/inch_ex/2.0.0-rc1 :+1:
