### ISSUE TITLE
Local Inch  set-up....

### ISSUE THREAD

**Issue by metelik** [rrrene/inch_ex#66]
The documentation is quite vague when it comes to this. INCH_PATH to inch... It does not mention where to get the executable from though.
Not everyone would like to connect to an external service to obtain a report - let's consider it as a privacy issue ;)

**Comment by tshakah** [comment]
I've created https://github.com/rrrene/inch_ex/pull/86 - this outputs the raw distribution numbers. It doesn't _quite_ solve your problem, but you could scrape the output and then pass it to the CLI tool?

`mix inch | grep -Po 'Grade values: \K([0-9]{1,3},\s){3}[0-9]{1,3}'` will get the raw numbers.

**Comment by rrrene** [comment]
@tshakah I think you misunderstood the context here. As far as I can tell @metelik is talking about the previous dependecy of InchEx v1 to either (a) the Ruby gem or (b) the internet service InchCI.

@metelik InchEx v2 does no longer depend on either of them and is implemented 100% in Elixir 🎉
